version: '3'
services:
  apache:
    container_name: apache
    image: paubarranca/debian-apache-php:v7.3
    restart: always
    volumes:
      - /srv/apache/www:/var/www/httpdocs
    ports:
      - "80:80"
    environment:
      - APACHE_ENABLE_CORS="false"
      - KEEPALIVE_MAX_REQUESTS="3500"
      - KEEPALIVE_TIMEOUT="600"
      - APACHE_START_SERVERS="2"
      - APACHE_MAX_REQUEST_WORKERS="250"
      - APACHE_DOCUMENTROOT="/var/www/"
      - APACHE_ENABLE_BADBOTS="true"
      - APACHE_ENABLE_CSP="false"
      - PHP_MEM_LIMIT="128M"
      - PHP_POST_MAX_SIZE="240M"
      - PHP_UPLOAD_MAX_FILESIZE="240M"
      - PHP_MAX_FILE_UPLOADS="20
      - PHP_DISPLAY_ERRORS="true"
      - PHP_ERROR_LOG_PATH="/dev/stdout"
      - PHP_MAX_EXECUTION_TIME="60"
      - PHP_SECURITY="false"

