version: '3'
services:
  redis:
    container_name: haproxy
    image: paubarranca/haproxy:v1
    restart: always
    network_mode: host
    volumes:
      -/srv/haproxy/certs:/etc/haproxy/certs
    ports:
      - "80:80"
      - "443:443"